# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robotOp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrobotOp.proto\"E\n\x04keys\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0e\n\x06\x63trKey\x18\x02 \x01(\x08\x12\x10\n\x08shiftKey\x18\x03 \x01(\x08\x12\x0e\n\x06\x61ltKey\x18\x04 \x01(\x08\"i\n\tOpRequest\x12\x11\n\tmouseType\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\x12\x13\n\x04keys\x18\x04 \x01(\x0b\x32\x05.keys\x12\x0e\n\x06\x64\x65ltaX\x18\x05 \x01(\x05\x12\x0e\n\x06\x64\x65ltaY\x18\x06 \x01(\x05\"\x18\n\x05Reply\x12\x0f\n\x07message\x18\x01 \x01(\t2*\n\x07robotOp\x12\x1f\n\x07Opmouse\x12\n.OpRequest\x1a\x06.Reply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robotOp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_KEYS']._serialized_start=17
  _globals['_KEYS']._serialized_end=86
  _globals['_OPREQUEST']._serialized_start=88
  _globals['_OPREQUEST']._serialized_end=193
  _globals['_REPLY']._serialized_start=195
  _globals['_REPLY']._serialized_end=219
  _globals['_ROBOTOP']._serialized_start=221
  _globals['_ROBOTOP']._serialized_end=263
# @@protoc_insertion_point(module_scope)
