# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import robotOp_pb2 as robotOp__pb2


class robotOpStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Opmouse = channel.unary_unary(
                '/robotOp/Opmouse',
                request_serializer=robotOp__pb2.OpRequest.SerializeToString,
                response_deserializer=robotOp__pb2.Reply.FromString,
                )


class robotOpServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Opmouse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_robotOpServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Opmouse': grpc.unary_unary_rpc_method_handler(
                    servicer.Opmouse,
                    request_deserializer=robotOp__pb2.OpRequest.FromString,
                    response_serializer=robotOp__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robotOp', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class robotOp(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Opmouse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robotOp/Opmouse',
            robotOp__pb2.OpRequest.SerializeToString,
            robotOp__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
